HOCS-3087 Use new workflow healthcheck in docker compose
UKHomeOffice/hocs pull request #10
Opened 2021-07-02 14:24 UTC by gardnersam

2021-07-02 14:53 UTC, philbarton approved these changes
Looks good to me

2021-07-06 12:24 UTC, philbarton approved these changes
Looks good to me

2021-07-06 12:32 UTC, philbarton requested changes

2021-07-06 12:32 UTC, philbarton commented on docker/docker-compose.yml
> +    healthcheck:
This health check isn't needed.

2021-07-06 14:38 UTC, gardnersam commented on docker/docker-compose.yml
> +    healthcheck:
I've removed it

2021-07-07 08:18 UTC, philbarton approved these changes
lgtm

2021-07-07 08:20 UTC, merged